### PR TITLE
chore: fix lint

### PR DESCRIPTION
**Pull request by pythonbrad**
### Related issues
- #21 

### Change
- Apply cargo clippy
- Fixed code formatting

### CODE REVIEW

**Comment by Mindful** [comment]
LGTM - just one request: can you add a line or two in the readme showing how to run whatever formatter you used to reformat the code (unless you did all the formatting manually...) ? I'm pretty unfamiliar with rust tooling.

**Comment by pythonbrad** [comment]
@Mindful 

`Cargo` comes with this tools.

- `cargo fmt`
- `cargo clippy`

If you don't use `cargo`, you can use `rustfmt`who comes with rust.

**Comment by pythonbrad** [comment]
To execute it, you can do 

`cargo fmt src/predict`

**Comment by Mindful** [comment]
Alright, good enough for me.

**Pull request merged**
