### PR TITLE
update the CMake project structure

### PR DESCRIPTION
**Pull request by pythonbrad**
### Related issues
- #12 

### Changes
- reorganized the code
- used corrosion-rs to build the rust library
- used standard GNU install directory

### Additional change
- updated the installation instructions of the docs
- enforced the build out-of-source to preserve a clean source code

### CODE REVIEW

**Comment by Mindful** [comment]
Thank you so much for the PR! I am probably not going to be able to test this properly until the weekend, so please give me a little bit of time to get back to you, but overall this looks great.
That said, I am probably going to ask you to revert deletions from the .gitignore file. 

Will get back to you within a week or so, thanks again!

**Comment by pythonbrad** [comment]
> That said, I am probably going to ask you to revert deletions from the .gitignore file.

@Mindful, I have reverted my changes in this `.gitignore` file. I understand that some IDEs or tools might generate files that we don't necessary want in the working tree. 💯

**Comment by pythonbrad** [comment]
@Mindful, in the meantime, if you have some improvement that you have for the project, you can make issues.
I am learning IBus currently, and I will be happy to help. 😄

**Comment by Mindful** [comment]
@pythonbrad 
This looks great and (perhaps more importantly) runs fine on my machine, so I'm going to merge it. 
Thanks again! 

> if you have some improvement that you have for the project, you can make issues.

There are a few things I considered over the years, mostly along the lines of adding some custom way for users to register new word completions or new emoji. This could be a UI or just a text/config file somewhere that was loaded instead of having to rebuild the project with different dictionaries.

That said, I don't have any strong opinions about adding stuff, so if there's something you think would be a good addition please feel free to suggest it (I.E. you are welcome to open issues as well). The only real important thing to me is that it doesn't slow anything down; I'd like to keep this responsive/fast since I use it. 

Also, for learning iBus in general, the best resources I found were the projects linked at the bottom of my readme. Reading those is how I figured out what I was doing well enough to implement this.

**Pull request merged**
